definitions:
  controllers.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  controllers.LoginCredentials:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  controllers.RegisterRequest:
    properties:
      email:
        type: string
      password:
        type: string
      phone_number:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - username
    type: object
  controllers.SuccessResponse:
    properties:
      data: {}
      message:
        type: string
    type: object
  controllers.VerificationRequest:
    properties:
      code:
        type: string
      email:
        type: string
    required:
    - code
    - email
    type: object
  models.Package:
    properties:
      categories:
        type: string
      created_at:
        type: string
      data:
        type: string
      deleted_at:
        type: string
      details:
        description: Override to string
        type: string
      duration:
        type: string
      id:
        type: integer
      name:
        type: string
      price:
        type: number
      updated_at:
        type: string
    type: object
info:
  contact: {}
  description: API untuk Mengelola Profil Pengguna
  title: Backend API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: This endpoint allows users to log in by providing email and password.
        A JWT token will be returned upon successful login.
      parameters:
      - description: User credentials (email and password)
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/controllers.LoginCredentials'
      produces:
      - application/json
      responses:
        "200":
          description: JWT token
          schema:
            $ref: '#/definitions/controllers.SuccessResponse'
        "400":
          description: Invalid request payload
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "401":
          description: Unauthorized, invalid credentials or email not verified
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "500":
          description: Error generating token or database error
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      summary: User login
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: This endpoint allows users to register by providing email, username,
        password, and phone number. A verification email will be sent after registration.
      parameters:
      - description: User registration data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/controllers.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Registration successful
          schema:
            $ref: '#/definitions/controllers.SuccessResponse'
        "400":
          description: Invalid request payload or password is empty
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "409":
          description: Email or username already exists
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "500":
          description: Error creating user or sending verification email
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      summary: Register a new user
      tags:
      - Auth
  /auth/verify-email:
    post:
      consumes:
      - application/json
      description: This endpoint allows users to verify their email by providing the
        verification code sent via email.
      parameters:
      - description: Email and verification code
        in: body
        name: verification
        required: true
        schema:
          $ref: '#/definitions/controllers.VerificationRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Email verified successfully
          schema:
            $ref: '#/definitions/controllers.SuccessResponse'
        "400":
          description: Invalid request payload or verification code
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
        "500":
          description: Failed to verify email
          schema:
            $ref: '#/definitions/controllers.ErrorResponse'
      summary: Verify user email
      tags:
      - Auth
  /packages:
    get:
      description: Retrieve a list of all available packages
      produces:
      - application/json
      responses:
        "200":
          description: List of available packages
          schema:
            items:
              $ref: '#/definitions/models.Package'
            type: array
        "500":
          description: Error fetching packages
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all packages
      tags:
      - Packages
  /packages/{id}:
    get:
      description: Retrieve a single package using its unique ID
      parameters:
      - description: Package ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Package details
          schema:
            $ref: '#/definitions/models.Package'
        "400":
          description: Invalid package ID
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Package not found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Error fetching package
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get a package by ID
      tags:
      - Packages
    post:
      description: Allows a user to select a package by its ID, updates the user's
        selected package
      parameters:
      - description: Package ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Package selected successfully, includes user and package information
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid package ID
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized, user not found in context
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: User not found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Database error or error updating user package
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Select a package
      tags:
      - Packages
swagger: "2.0"
